spring:
  datasource:
    username: postgres
    password: password123
    url: jdbc:postgresql://localhost:6500/testdb
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
